print("hello world")
name=input("hi there what is your name?")
print(name)
print("how are you?")
num1=input("enter first number:")
num2=input("enter secound number:")
sum= float(num1)+float(num2)
print(sum)
